server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/estudos-cloud/config-repo.git
          clone-on-start: true
          force-pull: true
          repos:
            app-a:
              patter: app-a-*
              uri: https://github.com/estudos-cloud/app-a-config.git
              force-pull: true

security:
  user:
    name: root
    password: s3cr3t
                